# Generated by Django 5.1.2 on 2024-10-29 14:12

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(default=users.models.generate_invitation_code, max_length=8, unique=True),
        ),
    ]
