# Generated by Django 5.1.2 on 2024-11-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_type',
            field=models.CharField(choices=[('solar', '阳历'), ('lunar', '农历')], default='solar', max_length=5, verbose_name='生日历法'),
        ),
    ]
