# Generated by Django 5.1.2 on 2024-10-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('short_name', models.CharField(max_length=50, verbose_name='项目简称')),
                ('year', models.IntegerField(verbose_name='年份')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-year', 'name'],
            },
        ),
    ]
