# Generated by Django 5.1.2 on 2024-10-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_tag_alter_uploadedfile_description_uploadedfile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
