# Generated by Django 5.1.2 on 2024-10-30 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_remove_uploadedfile_tags_delete_tag'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.project', verbose_name='所属项目'),
        ),
    ]
